const AppointmentActionTypes = {
    LOADING: "LOADING",
    GET_APPOINTMENTS: "GET_APPOINTMENTS",
    GET_APPOINTMENT: "GET_APPOINTMENT",
    ADD_APPOINTMENT: "ADD_APPOINTMENT",
    DELETE_APPOINMENT: "DELETE_APPOINMENT",
    UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
    FAILED_APPOINTMENT: "FAILED_APPOINTMENT",
}

export default AppointmentActionTypes;